### ISSUE TITLE
Training data HDR-Synth and HDR-Real URL  is wrong

### ISSUE THREAD

**Issue by mrunal2401** [ShinYwings/SingleHDR-tf2#1]
Please change the Training data url

![Screenshot 2023-03-28 at 6 11 29 PM](https://user-images.githubusercontent.com/122784951/228239166-5ba209f1-0c28-42bc-9c51-6276c1c99582.png)

**Comment by ShinYwings** [comment]
Sorry, this is a link provided by the original author, and I have no permission to redistribute this dataset. Please contact the official repository for inquiries.
